using AntilopeGP.Shared.Display;
using AntilopeGP.Shared.MVVM;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Reflection;
using Telerik.XamarinForms.Common;
using Telerik.XamarinForms.DataControls;
using Telerik.XamarinForms.DataControls.ListView;
using Telerik.XamarinForms.DataControls.ListView.Commands;
using Telerik.XamarinForms.Primitives;
using Xamarin.Forms;
using Xamarin.Forms.Internals;
using Xamarin.Forms.Xaml;
using Xamarin.Forms.Xaml.Diagnostics;
using Xamarin.Forms.Xaml.Internals;

namespace AntilopeGP.Shared.Views
{
	[XamlCompilation(XamlCompilationOptions.Compile)]
	[XamlFilePath("Views\\FiltreLignesPage.xaml")]
	public class FiltreLignesPage : ContentPage
	{
		private InsetsManager _insetsManager;

		public FiltreLignesPage(InsetsManager insetsManager)
		{
			_insetsManager = insetsManager;
			_insetsManager.StartManagingInsets(this);
			InitializeComponent();
		}

		[GeneratedCode("Xamarin.Forms.Build.Tasks.XamlG", "2.0.0.0")]
		private void InitializeComponent()
		{
			if (ResourceLoader.CanProvideContentFor(new ResourceLoader.ResourceLoadingQuery
			{
				AssemblyName = typeof(FiltreLignesPage).GetTypeInfo().Assembly.GetName(),
				ResourcePath = "Views/FiltreLignesPage.xaml",
				Instance = this
			}))
			{
				__InitComponentRuntime();
				return;
			}
			if (XamlLoader.XamlFileProvider != null && XamlLoader.XamlFileProvider(GetType()) != null)
			{
				__InitComponentRuntime();
				return;
			}
			NegateBooleanConverter value = new NegateBooleanConverter();
			CheckboxSelectedConverter value2 = new CheckboxSelectedConverter();
			BoolColorConverter boolColorConverter = new BoolColorConverter();
			ResourceDictionary resourceDictionary = new ResourceDictionary();
			ColumnDefinition columnDefinition = new ColumnDefinition();
			ColumnDefinition columnDefinition2 = new ColumnDefinition();
			StaticResourceExtension staticResourceExtension = new StaticResourceExtension();
			StaticResourceExtension staticResourceExtension2 = new StaticResourceExtension();
			Label label = new Label();
			StaticResourceExtension staticResourceExtension3 = new StaticResourceExtension();
			BindingExtension bindingExtension = new BindingExtension();
			BindingExtension bindingExtension2 = new BindingExtension();
			ImageButton imageButton = new ImageButton();
			RadBusyIndicator radBusyIndicator = new RadBusyIndicator();
			Grid grid = new Grid();
			ColumnDefinition columnDefinition3 = new ColumnDefinition();
			ColumnDefinition columnDefinition4 = new ColumnDefinition();
			StaticResourceExtension staticResourceExtension4 = new StaticResourceExtension();
			StaticResourceExtension staticResourceExtension5 = new StaticResourceExtension();
			Label label2 = new Label();
			BindingExtension bindingExtension3 = new BindingExtension();
			TapGestureRecognizer tapGestureRecognizer = new TapGestureRecognizer();
			BindingExtension bindingExtension4 = new BindingExtension();
			Setter setter = new Setter();
			DataTrigger dataTrigger = new DataTrigger(typeof(Image));
			Image image = new Image();
			Grid grid2 = new Grid();
			BindingExtension bindingExtension5 = new BindingExtension();
			ListViewLinearLayout listViewLinearLayout = new ListViewLinearLayout();
			PropertyGroupDescriptor propertyGroupDescriptor = new PropertyGroupDescriptor();
			DataTemplate dataTemplate = new DataTemplate();
			DataTemplate dataTemplate2 = new DataTemplate();
			ListViewItemStyle listViewItemStyle = new ListViewItemStyle();
			BindingExtension bindingExtension6 = new BindingExtension();
			ListViewUserCommand listViewUserCommand = new ListViewUserCommand();
			RadListView radListView = new RadListView();
			FlexLayout flexLayout = new FlexLayout();
			FiltreLignesPage filtreLignesPage;
			NameScope nameScope = (NameScope)(NameScope.GetNameScope(filtreLignesPage = this) ?? new NameScope());
			NameScope.SetNameScope(filtreLignesPage, nameScope);
			filtreLignesPage.Resources = resourceDictionary;
			VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 13, 10);
			resourceDictionary.Add("inverter", value);
			resourceDictionary.Add("checkboxSelectedConverter", value2);
			XamlServiceProvider xamlServiceProvider = new XamlServiceProvider();
			Type typeFromHandle = typeof(IProvideValueTarget);
			object[] array = new object[0 + 2];
			array[0] = resourceDictionary;
			array[1] = filtreLignesPage;
			object service;
			xamlServiceProvider.Add(typeFromHandle, service = new SimpleValueTargetProvider(array, null, nameScope));
			xamlServiceProvider.Add(typeof(IReferenceProvider), service);
			Type typeFromHandle2 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver = new XmlNamespaceResolver();
			xmlNamespaceResolver.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
			xmlNamespaceResolver.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
			xmlNamespaceResolver.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
			xmlNamespaceResolver.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
			xamlServiceProvider.Add(typeFromHandle2, new XamlTypeResolver(xmlNamespaceResolver, typeof(FiltreLignesPage).GetTypeInfo().Assembly));
			xamlServiceProvider.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(16, 14)));
			object value3 = ((IMarkupExtension)boolColorConverter).ProvideValue((IServiceProvider)xamlServiceProvider);
			resourceDictionary.Add("boolColorConverter", value3);
			filtreLignesPage.SetValue(NavigationPage.HasNavigationBarProperty, false);
			filtreLignesPage.Resources = resourceDictionary;
			VisualDiagnostics.RegisterSourceInfo(resourceDictionary, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 13, 10);
			flexLayout.SetValue(FlexLayout.DirectionProperty, new FlexDirectionTypeConverter().ConvertFromInvariantString("Column"));
			flexLayout.SetValue(FlexLayout.AlignItemsProperty, new FlexAlignItemsTypeConverter().ConvertFromInvariantString("Stretch"));
			flexLayout.SetValue(FlexLayout.JustifyContentProperty, new FlexJustifyTypeConverter().ConvertFromInvariantString("Start"));
			flexLayout.SetValue(FlexLayout.WrapProperty, new FlexWrapTypeConverter().ConvertFromInvariantString("NoWrap"));
			grid.SetValue(FlexLayout.ShrinkProperty, 0f);
			grid.SetValue(VisualElement.HeightRequestProperty, 60.0);
			columnDefinition.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition);
			columnDefinition2.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("60"));
			((DefinitionCollection<ColumnDefinition>)grid.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition2);
			label.SetValue(Label.TextProperty, "FILTRER MES LIGNES");
			staticResourceExtension.Key = "DarkGrayColor";
			XamlServiceProvider xamlServiceProvider2 = new XamlServiceProvider();
			Type typeFromHandle3 = typeof(IProvideValueTarget);
			object[] array2 = new object[0 + 4];
			array2[0] = label;
			array2[1] = grid;
			array2[2] = flexLayout;
			array2[3] = filtreLignesPage;
			object service2;
			xamlServiceProvider2.Add(typeFromHandle3, service2 = new SimpleValueTargetProvider(array2, Label.TextColorProperty, nameScope));
			xamlServiceProvider2.Add(typeof(IReferenceProvider), service2);
			Type typeFromHandle4 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver2 = new XmlNamespaceResolver();
			xmlNamespaceResolver2.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver2.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver2.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
			xmlNamespaceResolver2.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
			xmlNamespaceResolver2.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver2.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver2.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
			xmlNamespaceResolver2.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
			xamlServiceProvider2.Add(typeFromHandle4, new XamlTypeResolver(xmlNamespaceResolver2, typeof(FiltreLignesPage).GetTypeInfo().Assembly));
			xamlServiceProvider2.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(30, 20)));
			object obj = ((IMarkupExtension)staticResourceExtension).ProvideValue((IServiceProvider)xamlServiceProvider2);
			label.TextColor = (Color)obj;
			VisualDiagnostics.RegisterSourceInfo(obj, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 30, 20);
			staticResourceExtension2.Key = "TCLLight";
			XamlServiceProvider xamlServiceProvider3 = new XamlServiceProvider();
			Type typeFromHandle5 = typeof(IProvideValueTarget);
			object[] array3 = new object[0 + 4];
			array3[0] = label;
			array3[1] = grid;
			array3[2] = flexLayout;
			array3[3] = filtreLignesPage;
			object service3;
			xamlServiceProvider3.Add(typeFromHandle5, service3 = new SimpleValueTargetProvider(array3, Label.FontFamilyProperty, nameScope));
			xamlServiceProvider3.Add(typeof(IReferenceProvider), service3);
			Type typeFromHandle6 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver3 = new XmlNamespaceResolver();
			xmlNamespaceResolver3.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver3.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver3.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
			xmlNamespaceResolver3.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
			xmlNamespaceResolver3.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver3.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver3.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
			xmlNamespaceResolver3.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
			xamlServiceProvider3.Add(typeFromHandle6, new XamlTypeResolver(xmlNamespaceResolver3, typeof(FiltreLignesPage).GetTypeInfo().Assembly));
			xamlServiceProvider3.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(31, 20)));
			object target = label.FontFamily = (string)((IMarkupExtension)staticResourceExtension2).ProvideValue((IServiceProvider)xamlServiceProvider3);
			VisualDiagnostics.RegisterSourceInfo(target, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 31, 20);
			BindableProperty fontSizeProperty = Label.FontSizeProperty;
			FontSizeConverter fontSizeConverter = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider4 = new XamlServiceProvider();
			Type typeFromHandle7 = typeof(IProvideValueTarget);
			object[] array4 = new object[0 + 4];
			array4[0] = label;
			array4[1] = grid;
			array4[2] = flexLayout;
			array4[3] = filtreLignesPage;
			object service4;
			xamlServiceProvider4.Add(typeFromHandle7, service4 = new SimpleValueTargetProvider(array4, Label.FontSizeProperty, nameScope));
			xamlServiceProvider4.Add(typeof(IReferenceProvider), service4);
			Type typeFromHandle8 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver4 = new XmlNamespaceResolver();
			xmlNamespaceResolver4.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver4.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver4.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
			xmlNamespaceResolver4.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
			xmlNamespaceResolver4.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver4.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver4.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
			xmlNamespaceResolver4.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
			xamlServiceProvider4.Add(typeFromHandle8, new XamlTypeResolver(xmlNamespaceResolver4, typeof(FiltreLignesPage).GetTypeInfo().Assembly));
			xamlServiceProvider4.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(32, 20)));
			label.SetValue(fontSizeProperty, ((IExtendedTypeConverter)fontSizeConverter).ConvertFromInvariantString("Large", (IServiceProvider)xamlServiceProvider4));
			label.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label.SetValue(Label.HorizontalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
			label.SetValue(View.MarginProperty, new Thickness(0.0));
			label.SetValue(Grid.ColumnProperty, 0);
			label.SetValue(Grid.ColumnSpanProperty, 2);
			grid.Children.Add(label);
			VisualDiagnostics.RegisterSourceInfo(label, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 29, 14);
			radBusyIndicator.SetValue(RadBusyIndicator.AnimationContentHeightRequestProperty, 40.0);
			radBusyIndicator.SetValue(RadBusyIndicator.AnimationContentWidthRequestProperty, 40.0);
			radBusyIndicator.SetValue(RadBusyIndicator.AnimationTypeProperty, AnimationType.Animation6);
			staticResourceExtension3.Key = "TCLRed";
			XamlServiceProvider xamlServiceProvider5 = new XamlServiceProvider();
			Type typeFromHandle9 = typeof(IProvideValueTarget);
			object[] array5 = new object[0 + 4];
			array5[0] = radBusyIndicator;
			array5[1] = grid;
			array5[2] = flexLayout;
			array5[3] = filtreLignesPage;
			object service5;
			xamlServiceProvider5.Add(typeFromHandle9, service5 = new SimpleValueTargetProvider(array5, RadBusyIndicator.AnimationContentColorProperty, nameScope));
			xamlServiceProvider5.Add(typeof(IReferenceProvider), service5);
			Type typeFromHandle10 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver5 = new XmlNamespaceResolver();
			xmlNamespaceResolver5.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver5.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver5.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
			xmlNamespaceResolver5.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
			xmlNamespaceResolver5.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver5.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver5.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
			xmlNamespaceResolver5.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
			xamlServiceProvider5.Add(typeFromHandle10, new XamlTypeResolver(xmlNamespaceResolver5, typeof(FiltreLignesPage).GetTypeInfo().Assembly));
			xamlServiceProvider5.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(41, 49)));
			object obj2 = ((IMarkupExtension)staticResourceExtension3).ProvideValue((IServiceProvider)xamlServiceProvider5);
			radBusyIndicator.AnimationContentColor = (Color)obj2;
			VisualDiagnostics.RegisterSourceInfo(obj2, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 41, 49);
			radBusyIndicator.SetValue(Grid.ColumnProperty, 1);
			bindingExtension.Path = "IsBusy";
			BindingBase binding = ((IMarkupExtension<BindingBase>)bindingExtension).ProvideValue((IServiceProvider)null);
			radBusyIndicator.SetBinding(RadBusyIndicator.IsBusyProperty, binding);
			imageButton.SetValue(VisualElement.MinimumHeightRequestProperty, 40.0);
			imageButton.SetValue(VisualElement.MinimumWidthRequestProperty, 40.0);
			imageButton.SetValue(ImageButton.AspectProperty, Aspect.AspectFit);
			imageButton.SetValue(View.VerticalOptionsProperty, LayoutOptions.Center);
			imageButton.SetValue(View.HorizontalOptionsProperty, LayoutOptions.Center);
			imageButton.SetValue(ImageButton.SourceProperty, new ImageSourceConverter().ConvertFromInvariantString("valider.png"));
			imageButton.SetValue(VisualElement.BackgroundColorProperty, Color.White);
			bindingExtension2.Path = "CloseTapCommand";
			BindingBase binding2 = ((IMarkupExtension<BindingBase>)bindingExtension2).ProvideValue((IServiceProvider)null);
			imageButton.SetBinding(ImageButton.CommandProperty, binding2);
			radBusyIndicator.SetValue(RadBusyIndicator.ContentProperty, imageButton);
			VisualDiagnostics.RegisterSourceInfo(imageButton, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 45, 22);
			grid.Children.Add(radBusyIndicator);
			VisualDiagnostics.RegisterSourceInfo(radBusyIndicator, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 38, 14);
			flexLayout.Children.Add(grid);
			VisualDiagnostics.RegisterSourceInfo(grid, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 23, 10);
			grid2.SetValue(FlexLayout.ShrinkProperty, 0f);
			grid2.SetValue(VisualElement.HeightRequestProperty, 40.0);
			columnDefinition3.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("*"));
			((DefinitionCollection<ColumnDefinition>)grid2.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition3);
			columnDefinition4.SetValue(ColumnDefinition.WidthProperty, new GridLengthTypeConverter().ConvertFromInvariantString("50"));
			((DefinitionCollection<ColumnDefinition>)grid2.GetValue(Grid.ColumnDefinitionsProperty)).Add(columnDefinition4);
			label2.SetValue(Label.TextProperty, "Tout sélectionner");
			staticResourceExtension4.Key = "DarkGrayColor";
			XamlServiceProvider xamlServiceProvider6 = new XamlServiceProvider();
			Type typeFromHandle11 = typeof(IProvideValueTarget);
			object[] array6 = new object[0 + 4];
			array6[0] = label2;
			array6[1] = grid2;
			array6[2] = flexLayout;
			array6[3] = filtreLignesPage;
			object service6;
			xamlServiceProvider6.Add(typeFromHandle11, service6 = new SimpleValueTargetProvider(array6, Label.TextColorProperty, nameScope));
			xamlServiceProvider6.Add(typeof(IReferenceProvider), service6);
			Type typeFromHandle12 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver6 = new XmlNamespaceResolver();
			xmlNamespaceResolver6.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver6.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver6.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
			xmlNamespaceResolver6.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
			xmlNamespaceResolver6.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver6.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver6.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
			xmlNamespaceResolver6.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
			xamlServiceProvider6.Add(typeFromHandle12, new XamlTypeResolver(xmlNamespaceResolver6, typeof(FiltreLignesPage).GetTypeInfo().Assembly));
			xamlServiceProvider6.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(63, 20)));
			object obj3 = ((IMarkupExtension)staticResourceExtension4).ProvideValue((IServiceProvider)xamlServiceProvider6);
			label2.TextColor = (Color)obj3;
			VisualDiagnostics.RegisterSourceInfo(obj3, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 63, 20);
			staticResourceExtension5.Key = "TCLRegular";
			XamlServiceProvider xamlServiceProvider7 = new XamlServiceProvider();
			Type typeFromHandle13 = typeof(IProvideValueTarget);
			object[] array7 = new object[0 + 4];
			array7[0] = label2;
			array7[1] = grid2;
			array7[2] = flexLayout;
			array7[3] = filtreLignesPage;
			object service7;
			xamlServiceProvider7.Add(typeFromHandle13, service7 = new SimpleValueTargetProvider(array7, Label.FontFamilyProperty, nameScope));
			xamlServiceProvider7.Add(typeof(IReferenceProvider), service7);
			Type typeFromHandle14 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver7 = new XmlNamespaceResolver();
			xmlNamespaceResolver7.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver7.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver7.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
			xmlNamespaceResolver7.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
			xmlNamespaceResolver7.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver7.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver7.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
			xmlNamespaceResolver7.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
			xamlServiceProvider7.Add(typeFromHandle14, new XamlTypeResolver(xmlNamespaceResolver7, typeof(FiltreLignesPage).GetTypeInfo().Assembly));
			xamlServiceProvider7.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(64, 20)));
			object target2 = label2.FontFamily = (string)((IMarkupExtension)staticResourceExtension5).ProvideValue((IServiceProvider)xamlServiceProvider7);
			VisualDiagnostics.RegisterSourceInfo(target2, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 64, 20);
			BindableProperty fontSizeProperty2 = Label.FontSizeProperty;
			FontSizeConverter fontSizeConverter2 = new FontSizeConverter();
			XamlServiceProvider xamlServiceProvider8 = new XamlServiceProvider();
			Type typeFromHandle15 = typeof(IProvideValueTarget);
			object[] array8 = new object[0 + 4];
			array8[0] = label2;
			array8[1] = grid2;
			array8[2] = flexLayout;
			array8[3] = filtreLignesPage;
			object service8;
			xamlServiceProvider8.Add(typeFromHandle15, service8 = new SimpleValueTargetProvider(array8, Label.FontSizeProperty, nameScope));
			xamlServiceProvider8.Add(typeof(IReferenceProvider), service8);
			Type typeFromHandle16 = typeof(IXamlTypeResolver);
			XmlNamespaceResolver xmlNamespaceResolver8 = new XmlNamespaceResolver();
			xmlNamespaceResolver8.Add("", "http://xamarin.com/schemas/2014/forms");
			xmlNamespaceResolver8.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
			xmlNamespaceResolver8.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
			xmlNamespaceResolver8.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
			xmlNamespaceResolver8.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver8.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
			xmlNamespaceResolver8.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
			xmlNamespaceResolver8.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
			xamlServiceProvider8.Add(typeFromHandle16, new XamlTypeResolver(xmlNamespaceResolver8, typeof(FiltreLignesPage).GetTypeInfo().Assembly));
			xamlServiceProvider8.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(65, 20)));
			label2.SetValue(fontSizeProperty2, ((IExtendedTypeConverter)fontSizeConverter2).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider8));
			label2.SetValue(View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
			label2.SetValue(View.VerticalOptionsProperty, LayoutOptions.Center);
			label2.SetValue(View.HorizontalOptionsProperty, LayoutOptions.Start);
			label2.SetValue(Grid.ColumnProperty, 0);
			grid2.Children.Add(label2);
			VisualDiagnostics.RegisterSourceInfo(label2, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 62, 14);
			image.SetValue(Grid.ColumnProperty, 1);
			image.SetValue(VisualElement.HeightRequestProperty, 25.0);
			image.SetValue(View.VerticalOptionsProperty, LayoutOptions.Center);
			image.SetValue(View.HorizontalOptionsProperty, LayoutOptions.Center);
			image.SetValue(Image.AspectProperty, Aspect.AspectFit);
			image.SetValue(Image.SourceProperty, new ImageSourceConverter().ConvertFromInvariantString("checkbox.png"));
			image.SetValue(VisualElement.BackgroundColorProperty, Color.White);
			bindingExtension3.Path = "SelectAllTapCommand";
			BindingBase binding3 = ((IMarkupExtension<BindingBase>)bindingExtension3).ProvideValue((IServiceProvider)null);
			tapGestureRecognizer.SetBinding(TapGestureRecognizer.CommandProperty, binding3);
			image.GestureRecognizers.Add(tapGestureRecognizer);
			VisualDiagnostics.RegisterSourceInfo(tapGestureRecognizer, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 78, 22);
			bindingExtension4.Path = "AllLignesSelected";
			BindingBase target3 = dataTrigger.Binding = ((IMarkupExtension<BindingBase>)bindingExtension4).ProvideValue((IServiceProvider)null);
			VisualDiagnostics.RegisterSourceInfo(target3, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 82, 34);
			dataTrigger.Value = "True";
			setter.Property = Image.SourceProperty;
			setter.Value = "checkboxchecked_red.png";
			setter.Value = new ImageSourceConverter().ConvertFromInvariantString("checkboxchecked_red.png");
			dataTrigger.Setters.Add(setter);
			VisualDiagnostics.RegisterSourceInfo(setter, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 84, 26);
			((ICollection<TriggerBase>)image.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger);
			VisualDiagnostics.RegisterSourceInfo(dataTrigger, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 81, 22);
			grid2.Children.Add(image);
			VisualDiagnostics.RegisterSourceInfo(image, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 70, 14);
			flexLayout.Children.Add(grid2);
			VisualDiagnostics.RegisterSourceInfo(grid2, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 56, 10);
			radListView.SetValue(RadListView.SelectionModeProperty, Telerik.XamarinForms.DataControls.ListView.SelectionMode.None);
			bindingExtension5.Path = "Lignes";
			BindingBase binding4 = ((IMarkupExtension<BindingBase>)bindingExtension5).ProvideValue((IServiceProvider)null);
			radListView.SetBinding(RadListView.ItemsSourceProperty, binding4);
			listViewLinearLayout.SetValue(ListViewLayoutBase.GroupHeaderLengthProperty, 30.0);
			listViewLinearLayout.SetValue(ListViewLayoutBase.ItemLengthProperty, 40.0);
			listViewLinearLayout.SetValue(ListViewLayoutBase.VerticalItemSpacingProperty, 0.0);
			radListView.SetValue(RadListView.LayoutDefinitionProperty, listViewLinearLayout);
			VisualDiagnostics.RegisterSourceInfo(listViewLinearLayout, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 93, 18);
			propertyGroupDescriptor.SetValue(PropertyGroupDescriptor.PropertyNameProperty, "Proximity");
			propertyGroupDescriptor.SetValue(OrderedDescriptorBase.SortOrderProperty, SortOrder.Descending);
			((Collection<GroupDescriptorBase>)radListView.GetValue(RadListView.GroupDescriptorsProperty)).Add((GroupDescriptorBase)propertyGroupDescriptor);
			VisualDiagnostics.RegisterSourceInfo(propertyGroupDescriptor, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 98, 18);
			object[] array9 = new object[0 + 4];
			array9[0] = dataTemplate;
			array9[1] = radListView;
			array9[2] = flexLayout;
			array9[3] = filtreLignesPage;
			object[] parentValues2 = array9;
			FiltreLignesPage root2 = filtreLignesPage;
			((IDataTemplate)dataTemplate).LoadTemplate = delegate
			{
				StaticResourceExtension staticResourceExtension9 = new StaticResourceExtension();
				StaticResourceExtension staticResourceExtension10 = new StaticResourceExtension();
				BindingExtension bindingExtension19 = new BindingExtension();
				Setter setter8 = new Setter();
				Setter setter9 = new Setter();
				DataTrigger dataTrigger6 = new DataTrigger(typeof(RadBorder));
				StaticResourceExtension staticResourceExtension11 = new StaticResourceExtension();
				BindingExtension bindingExtension20 = new BindingExtension();
				Setter setter10 = new Setter();
				DataTrigger dataTrigger7 = new DataTrigger(typeof(Label));
				Label label4 = new Label();
				RadBorder radBorder = new RadBorder();
				NameScope nameScope3 = new NameScope();
				NameScope.SetNameScope(radBorder, nameScope3);
				radBorder.SetValue(Grid.ColumnSpanProperty, 2);
				radBorder.SetValue(View.HorizontalOptionsProperty, LayoutOptions.FillAndExpand);
				radBorder.SetValue(View.VerticalOptionsProperty, LayoutOptions.FillAndExpand);
				radBorder.SetValue(View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
				staticResourceExtension9.Key = "TCLRed";
				XamlServiceProvider xamlServiceProvider13 = new XamlServiceProvider();
				Type typeFromHandle25 = typeof(IProvideValueTarget);
				int length5;
				object[] array15 = new object[(length5 = parentValues2.Length) + 1];
				Array.Copy(parentValues2, 0, array15, 1, length5);
				array15[0] = radBorder;
				object service13;
				xamlServiceProvider13.Add(typeFromHandle25, service13 = new SimpleValueTargetProvider(array15, VisualElement.BackgroundColorProperty, nameScope3));
				xamlServiceProvider13.Add(typeof(IReferenceProvider), service13);
				Type typeFromHandle26 = typeof(IXamlTypeResolver);
				XmlNamespaceResolver xmlNamespaceResolver13 = new XmlNamespaceResolver();
				xmlNamespaceResolver13.Add("", "http://xamarin.com/schemas/2014/forms");
				xmlNamespaceResolver13.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
				xmlNamespaceResolver13.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
				xmlNamespaceResolver13.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
				xmlNamespaceResolver13.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver13.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver13.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
				xmlNamespaceResolver13.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
				xamlServiceProvider13.Add(typeFromHandle26, new XamlTypeResolver(xmlNamespaceResolver13, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_4).GetTypeInfo().Assembly));
				xamlServiceProvider13.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(107, 50)));
				object obj6 = ((IMarkupExtension)staticResourceExtension9).ProvideValue((IServiceProvider)xamlServiceProvider13);
				radBorder.BackgroundColor = (Color)obj6;
				VisualDiagnostics.RegisterSourceInfo(obj6, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 107, 50);
				staticResourceExtension10.Key = "TCLRed";
				XamlServiceProvider xamlServiceProvider14 = new XamlServiceProvider();
				Type typeFromHandle27 = typeof(IProvideValueTarget);
				int length6;
				object[] array16 = new object[(length6 = parentValues2.Length) + 1];
				Array.Copy(parentValues2, 0, array16, 1, length6);
				array16[0] = radBorder;
				object service14;
				xamlServiceProvider14.Add(typeFromHandle27, service14 = new SimpleValueTargetProvider(array16, RadBorder.BorderColorProperty, nameScope3));
				xamlServiceProvider14.Add(typeof(IReferenceProvider), service14);
				Type typeFromHandle28 = typeof(IXamlTypeResolver);
				XmlNamespaceResolver xmlNamespaceResolver14 = new XmlNamespaceResolver();
				xmlNamespaceResolver14.Add("", "http://xamarin.com/schemas/2014/forms");
				xmlNamespaceResolver14.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
				xmlNamespaceResolver14.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
				xmlNamespaceResolver14.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
				xmlNamespaceResolver14.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver14.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver14.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
				xmlNamespaceResolver14.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
				xamlServiceProvider14.Add(typeFromHandle28, new XamlTypeResolver(xmlNamespaceResolver14, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_4).GetTypeInfo().Assembly));
				xamlServiceProvider14.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(108, 50)));
				object obj7 = ((IMarkupExtension)staticResourceExtension10).ProvideValue((IServiceProvider)xamlServiceProvider14);
				radBorder.BorderColor = (Color)obj7;
				VisualDiagnostics.RegisterSourceInfo(obj7, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 108, 50);
				radBorder.SetValue(RadBorder.BorderThicknessProperty, new Thickness(1.0));
				radBorder.SetValue(RadBorder.CornerRadiusProperty, new Thickness(10.0, 0.0, 0.0, 10.0));
				bindingExtension19.Path = "Key";
				BindingBase target14 = dataTrigger6.Binding = ((IMarkupExtension<BindingBase>)bindingExtension19).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target14, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 113, 42);
				dataTrigger6.Value = "False";
				setter8.Property = VisualElement.BackgroundColorProperty;
				setter8.Value = "#706F6F";
				setter8.Value = new Color(0.43921568989753723, 0.43529412150382996, 0.43529412150382996, 1.0);
				dataTrigger6.Setters.Add(setter8);
				VisualDiagnostics.RegisterSourceInfo(setter8, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 115, 34);
				setter9.Property = RadBorder.BorderColorProperty;
				setter9.Value = "#706F6F";
				setter9.Value = new Color(0.43921568989753723, 0.43529412150382996, 0.43529412150382996, 1.0);
				dataTrigger6.Setters.Add(setter9);
				VisualDiagnostics.RegisterSourceInfo(setter9, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 117, 34);
				((ICollection<TriggerBase>)radBorder.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger6);
				VisualDiagnostics.RegisterSourceInfo(dataTrigger6, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 112, 30);
				label4.SetValue(Label.TextProperty, "Lignes à proximité");
				label4.SetValue(Label.TextColorProperty, Color.White);
				staticResourceExtension11.Key = "TCLRegular";
				XamlServiceProvider xamlServiceProvider15 = new XamlServiceProvider();
				Type typeFromHandle29 = typeof(IProvideValueTarget);
				int length7;
				object[] array17 = new object[(length7 = parentValues2.Length) + 2];
				Array.Copy(parentValues2, 0, array17, 2, length7);
				array17[0] = label4;
				array17[1] = radBorder;
				object service15;
				xamlServiceProvider15.Add(typeFromHandle29, service15 = new SimpleValueTargetProvider(array17, Label.FontFamilyProperty, nameScope3));
				xamlServiceProvider15.Add(typeof(IReferenceProvider), service15);
				Type typeFromHandle30 = typeof(IXamlTypeResolver);
				XmlNamespaceResolver xmlNamespaceResolver15 = new XmlNamespaceResolver();
				xmlNamespaceResolver15.Add("", "http://xamarin.com/schemas/2014/forms");
				xmlNamespaceResolver15.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
				xmlNamespaceResolver15.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
				xmlNamespaceResolver15.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
				xmlNamespaceResolver15.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver15.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver15.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
				xmlNamespaceResolver15.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
				xamlServiceProvider15.Add(typeFromHandle30, new XamlTypeResolver(xmlNamespaceResolver15, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_4).GetTypeInfo().Assembly));
				xamlServiceProvider15.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(123, 32)));
				object target15 = label4.FontFamily = (string)((IMarkupExtension)staticResourceExtension11).ProvideValue((IServiceProvider)xamlServiceProvider15);
				VisualDiagnostics.RegisterSourceInfo(target15, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 123, 32);
				BindableProperty fontSizeProperty4 = Label.FontSizeProperty;
				FontSizeConverter fontSizeConverter4 = new FontSizeConverter();
				XamlServiceProvider xamlServiceProvider16 = new XamlServiceProvider();
				Type typeFromHandle31 = typeof(IProvideValueTarget);
				int length8;
				object[] array18 = new object[(length8 = parentValues2.Length) + 2];
				Array.Copy(parentValues2, 0, array18, 2, length8);
				array18[0] = label4;
				array18[1] = radBorder;
				object service16;
				xamlServiceProvider16.Add(typeFromHandle31, service16 = new SimpleValueTargetProvider(array18, Label.FontSizeProperty, nameScope3));
				xamlServiceProvider16.Add(typeof(IReferenceProvider), service16);
				Type typeFromHandle32 = typeof(IXamlTypeResolver);
				XmlNamespaceResolver xmlNamespaceResolver16 = new XmlNamespaceResolver();
				xmlNamespaceResolver16.Add("", "http://xamarin.com/schemas/2014/forms");
				xmlNamespaceResolver16.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
				xmlNamespaceResolver16.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
				xmlNamespaceResolver16.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
				xmlNamespaceResolver16.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver16.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver16.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
				xmlNamespaceResolver16.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
				xamlServiceProvider16.Add(typeFromHandle32, new XamlTypeResolver(xmlNamespaceResolver16, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_4).GetTypeInfo().Assembly));
				xamlServiceProvider16.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(124, 32)));
				label4.SetValue(fontSizeProperty4, ((IExtendedTypeConverter)fontSizeConverter4).ConvertFromInvariantString("Medium", (IServiceProvider)xamlServiceProvider16));
				label4.SetValue(View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
				label4.SetValue(Label.VerticalTextAlignmentProperty, new TextAlignmentConverter().ConvertFromInvariantString("Center"));
				bindingExtension20.Path = "Key";
				BindingBase target16 = dataTrigger7.Binding = ((IMarkupExtension<BindingBase>)bindingExtension20).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target16, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 129, 46);
				dataTrigger7.Value = "False";
				setter10.Property = Label.TextProperty;
				setter10.Value = "Autres lignes";
				setter10.Value = "Autres lignes";
				dataTrigger7.Setters.Add(setter10);
				VisualDiagnostics.RegisterSourceInfo(setter10, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 131, 38);
				((ICollection<TriggerBase>)label4.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger7);
				VisualDiagnostics.RegisterSourceInfo(dataTrigger7, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 128, 34);
				radBorder.SetValue(ContentView.ContentProperty, label4);
				VisualDiagnostics.RegisterSourceInfo(label4, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 121, 26);
				return radBorder;
			};
			radListView.SetValue(RadListView.GroupHeaderTemplateProperty, dataTemplate);
			VisualDiagnostics.RegisterSourceInfo(dataTemplate, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 102, 18);
			object[] array10 = new object[0 + 4];
			array10[0] = dataTemplate2;
			array10[1] = radListView;
			array10[2] = flexLayout;
			array10[3] = filtreLignesPage;
			object[] parentValues = array10;
			FiltreLignesPage root = filtreLignesPage;
			((IDataTemplate)dataTemplate2).LoadTemplate = delegate
			{
				BindingExtension bindingExtension7 = new BindingExtension();
				BindingExtension bindingExtension8 = new BindingExtension();
				BindingExtension bindingExtension9 = new BindingExtension();
				Setter setter2 = new Setter();
				DataTrigger dataTrigger2 = new DataTrigger(typeof(Image));
				Image image2 = new Image();
				BindingExtension bindingExtension10 = new BindingExtension();
				BindingExtension bindingExtension11 = new BindingExtension();
				Setter setter3 = new Setter();
				DataTrigger dataTrigger3 = new DataTrigger(typeof(Image));
				Image image3 = new Image();
				BindingExtension bindingExtension12 = new BindingExtension();
				StaticResourceExtension staticResourceExtension6 = new StaticResourceExtension();
				StaticResourceExtension staticResourceExtension7 = new StaticResourceExtension();
				BindingExtension bindingExtension13 = new BindingExtension();
				StaticResourceExtension staticResourceExtension8 = new StaticResourceExtension();
				Setter setter4 = new Setter();
				DataTrigger dataTrigger4 = new DataTrigger(typeof(Label));
				Label label3 = new Label();
				BindingExtension bindingExtension14 = new BindingExtension();
				BindingCondition bindingCondition = new BindingCondition();
				BindingExtension bindingExtension15 = new BindingExtension();
				BindingCondition bindingCondition2 = new BindingCondition();
				Setter setter5 = new Setter();
				MultiTrigger multiTrigger = new MultiTrigger(typeof(Image));
				BindingExtension bindingExtension16 = new BindingExtension();
				BindingCondition bindingCondition3 = new BindingCondition();
				BindingExtension bindingExtension17 = new BindingExtension();
				BindingCondition bindingCondition4 = new BindingCondition();
				Setter setter6 = new Setter();
				MultiTrigger multiTrigger2 = new MultiTrigger(typeof(Image));
				BindingExtension bindingExtension18 = new BindingExtension();
				Setter setter7 = new Setter();
				DataTrigger dataTrigger5 = new DataTrigger(typeof(Image));
				Image image4 = new Image();
				FlexLayout flexLayout2 = new FlexLayout();
				ListViewTemplateCell listViewTemplateCell = new ListViewTemplateCell();
				NameScope nameScope2 = new NameScope();
				NameScope.SetNameScope(listViewTemplateCell, nameScope2);
				flexLayout2.SetValue(FlexLayout.DirectionProperty, new FlexDirectionTypeConverter().ConvertFromInvariantString("Row"));
				flexLayout2.SetValue(FlexLayout.AlignItemsProperty, new FlexAlignItemsTypeConverter().ConvertFromInvariantString("Center"));
				flexLayout2.SetValue(FlexLayout.JustifyContentProperty, new FlexJustifyTypeConverter().ConvertFromInvariantString("SpaceBetween"));
				bindingExtension7.Path = "BackgroundColor";
				BindingBase binding6 = ((IMarkupExtension<BindingBase>)bindingExtension7).ProvideValue((IServiceProvider)null);
				flexLayout2.SetBinding(VisualElement.BackgroundColorProperty, binding6);
				image2.SetValue(VisualElement.HeightRequestProperty, 25.0);
				image2.SetValue(Image.AspectProperty, Aspect.AspectFit);
				image2.SetValue(View.MarginProperty, new Thickness(10.0, 0.0, 0.0, 0.0));
				bindingExtension8.Path = "ModeImagePath";
				BindingBase binding7 = ((IMarkupExtension<BindingBase>)bindingExtension8).ProvideValue((IServiceProvider)null);
				image2.SetBinding(Image.SourceProperty, binding7);
				bindingExtension9.Path = "Selected";
				BindingBase target4 = dataTrigger2.Binding = ((IMarkupExtension<BindingBase>)bindingExtension9).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target4, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 153, 54);
				dataTrigger2.Value = "False";
				setter2.Property = VisualElement.OpacityProperty;
				setter2.Value = "0.5";
				setter2.Value = 0.5;
				dataTrigger2.Setters.Add(setter2);
				VisualDiagnostics.RegisterSourceInfo(setter2, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 155, 46);
				((ICollection<TriggerBase>)image2.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger2);
				VisualDiagnostics.RegisterSourceInfo(dataTrigger2, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 152, 42);
				flexLayout2.Children.Add(image2);
				VisualDiagnostics.RegisterSourceInfo(image2, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 147, 34);
				image3.SetValue(VisualElement.HeightRequestProperty, 25.0);
				image3.SetValue(Image.AspectProperty, Aspect.AspectFit);
				image3.SetValue(View.MarginProperty, new Thickness(2.0, 0.0, 0.0, 0.0));
				bindingExtension10.Path = "LigneImagePath";
				BindingBase binding8 = ((IMarkupExtension<BindingBase>)bindingExtension10).ProvideValue((IServiceProvider)null);
				image3.SetBinding(Image.SourceProperty, binding8);
				bindingExtension11.Path = "Selected";
				BindingBase target5 = dataTrigger3.Binding = ((IMarkupExtension<BindingBase>)bindingExtension11).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target5, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 166, 54);
				dataTrigger3.Value = "False";
				setter3.Property = VisualElement.OpacityProperty;
				setter3.Value = "0.5";
				setter3.Value = 0.5;
				dataTrigger3.Setters.Add(setter3);
				VisualDiagnostics.RegisterSourceInfo(setter3, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 168, 46);
				((ICollection<TriggerBase>)image3.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger3);
				VisualDiagnostics.RegisterSourceInfo(dataTrigger3, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 165, 42);
				flexLayout2.Children.Add(image3);
				VisualDiagnostics.RegisterSourceInfo(image3, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 160, 34);
				bindingExtension12.Path = "Destination";
				BindingBase binding9 = ((IMarkupExtension<BindingBase>)bindingExtension12).ProvideValue((IServiceProvider)null);
				label3.SetBinding(Label.TextProperty, binding9);
				staticResourceExtension6.Key = "DarkGrayColor";
				XamlServiceProvider xamlServiceProvider9 = new XamlServiceProvider();
				Type typeFromHandle17 = typeof(IProvideValueTarget);
				int length;
				object[] array11 = new object[(length = parentValues.Length) + 3];
				Array.Copy(parentValues, 0, array11, 3, length);
				array11[0] = label3;
				array11[1] = flexLayout2;
				array11[2] = listViewTemplateCell;
				object service9;
				xamlServiceProvider9.Add(typeFromHandle17, service9 = new SimpleValueTargetProvider(array11, Label.TextColorProperty, nameScope2));
				xamlServiceProvider9.Add(typeof(IReferenceProvider), service9);
				Type typeFromHandle18 = typeof(IXamlTypeResolver);
				XmlNamespaceResolver xmlNamespaceResolver9 = new XmlNamespaceResolver();
				xmlNamespaceResolver9.Add("", "http://xamarin.com/schemas/2014/forms");
				xmlNamespaceResolver9.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
				xmlNamespaceResolver9.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
				xmlNamespaceResolver9.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
				xmlNamespaceResolver9.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver9.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver9.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
				xmlNamespaceResolver9.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
				xamlServiceProvider9.Add(typeFromHandle18, new XamlTypeResolver(xmlNamespaceResolver9, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
				xamlServiceProvider9.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(174, 40)));
				object obj4 = ((IMarkupExtension)staticResourceExtension6).ProvideValue((IServiceProvider)xamlServiceProvider9);
				label3.TextColor = (Color)obj4;
				VisualDiagnostics.RegisterSourceInfo(obj4, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 174, 40);
				staticResourceExtension7.Key = "TCLRegular";
				XamlServiceProvider xamlServiceProvider10 = new XamlServiceProvider();
				Type typeFromHandle19 = typeof(IProvideValueTarget);
				int length2;
				object[] array12 = new object[(length2 = parentValues.Length) + 3];
				Array.Copy(parentValues, 0, array12, 3, length2);
				array12[0] = label3;
				array12[1] = flexLayout2;
				array12[2] = listViewTemplateCell;
				object service10;
				xamlServiceProvider10.Add(typeFromHandle19, service10 = new SimpleValueTargetProvider(array12, Label.FontFamilyProperty, nameScope2));
				xamlServiceProvider10.Add(typeof(IReferenceProvider), service10);
				Type typeFromHandle20 = typeof(IXamlTypeResolver);
				XmlNamespaceResolver xmlNamespaceResolver10 = new XmlNamespaceResolver();
				xmlNamespaceResolver10.Add("", "http://xamarin.com/schemas/2014/forms");
				xmlNamespaceResolver10.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
				xmlNamespaceResolver10.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
				xmlNamespaceResolver10.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
				xmlNamespaceResolver10.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver10.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver10.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
				xmlNamespaceResolver10.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
				xamlServiceProvider10.Add(typeFromHandle20, new XamlTypeResolver(xmlNamespaceResolver10, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
				xamlServiceProvider10.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(175, 40)));
				object target6 = label3.FontFamily = (string)((IMarkupExtension)staticResourceExtension7).ProvideValue((IServiceProvider)xamlServiceProvider10);
				VisualDiagnostics.RegisterSourceInfo(target6, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 175, 40);
				BindableProperty fontSizeProperty3 = Label.FontSizeProperty;
				FontSizeConverter fontSizeConverter3 = new FontSizeConverter();
				XamlServiceProvider xamlServiceProvider11 = new XamlServiceProvider();
				Type typeFromHandle21 = typeof(IProvideValueTarget);
				int length3;
				object[] array13 = new object[(length3 = parentValues.Length) + 3];
				Array.Copy(parentValues, 0, array13, 3, length3);
				array13[0] = label3;
				array13[1] = flexLayout2;
				array13[2] = listViewTemplateCell;
				object service11;
				xamlServiceProvider11.Add(typeFromHandle21, service11 = new SimpleValueTargetProvider(array13, Label.FontSizeProperty, nameScope2));
				xamlServiceProvider11.Add(typeof(IReferenceProvider), service11);
				Type typeFromHandle22 = typeof(IXamlTypeResolver);
				XmlNamespaceResolver xmlNamespaceResolver11 = new XmlNamespaceResolver();
				xmlNamespaceResolver11.Add("", "http://xamarin.com/schemas/2014/forms");
				xmlNamespaceResolver11.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
				xmlNamespaceResolver11.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
				xmlNamespaceResolver11.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
				xmlNamespaceResolver11.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver11.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver11.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
				xmlNamespaceResolver11.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
				xamlServiceProvider11.Add(typeFromHandle22, new XamlTypeResolver(xmlNamespaceResolver11, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
				xamlServiceProvider11.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(176, 40)));
				label3.SetValue(fontSizeProperty3, ((IExtendedTypeConverter)fontSizeConverter3).ConvertFromInvariantString("Default", (IServiceProvider)xamlServiceProvider11));
				label3.SetValue(Label.LineBreakModeProperty, LineBreakMode.TailTruncation);
				label3.SetValue(View.MarginProperty, new Thickness(5.0, 0.0, 0.0, 0.0));
				label3.SetValue(FlexLayout.GrowProperty, 1f);
				bindingExtension13.Path = "Selected";
				BindingBase target7 = dataTrigger4.Binding = ((IMarkupExtension<BindingBase>)bindingExtension13).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target7, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 182, 54);
				dataTrigger4.Value = "False";
				setter4.Property = Label.TextColorProperty;
				staticResourceExtension8.Key = "DisabledGrayColor";
				XamlServiceProvider xamlServiceProvider12 = new XamlServiceProvider();
				Type typeFromHandle23 = typeof(IProvideValueTarget);
				int length4;
				object[] array14 = new object[(length4 = parentValues.Length) + 5];
				Array.Copy(parentValues, 0, array14, 5, length4);
				array14[0] = setter4;
				array14[1] = dataTrigger4;
				array14[2] = label3;
				array14[3] = flexLayout2;
				array14[4] = listViewTemplateCell;
				object service12;
				xamlServiceProvider12.Add(typeFromHandle23, service12 = new SimpleValueTargetProvider(array14, typeof(Setter).GetRuntimeProperty("Value"), nameScope2));
				xamlServiceProvider12.Add(typeof(IReferenceProvider), service12);
				Type typeFromHandle24 = typeof(IXamlTypeResolver);
				XmlNamespaceResolver xmlNamespaceResolver12 = new XmlNamespaceResolver();
				xmlNamespaceResolver12.Add("", "http://xamarin.com/schemas/2014/forms");
				xmlNamespaceResolver12.Add("x", "http://schemas.microsoft.com/winfx/2009/xaml");
				xmlNamespaceResolver12.Add("mvvm", "clr-namespace:AntilopeGP.Shared.MVVM");
				xmlNamespaceResolver12.Add("controls", "clr-namespace:AntilopeGP.Shared.Controls");
				xmlNamespaceResolver12.Add("telerikDataControls", "clr-namespace:Telerik.XamarinForms.DataControls;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver12.Add("telerikListView", "clr-namespace:Telerik.XamarinForms.DataControls.ListView;assembly=Telerik.XamarinForms.DataControls");
				xmlNamespaceResolver12.Add("telerikPrimitives", "clr-namespace:Telerik.XamarinForms.Primitives;assembly=Telerik.XamarinForms.Primitives");
				xmlNamespaceResolver12.Add("telerikListViewCommands", "clr-namespace:Telerik.XamarinForms.DataControls.ListView.Commands;assembly=Telerik.XamarinForms.DataControls");
				xamlServiceProvider12.Add(typeFromHandle24, new XamlTypeResolver(xmlNamespaceResolver12, typeof(_003CInitializeComponent_003E_anonXamlCDataTemplate_5).GetTypeInfo().Assembly));
				xamlServiceProvider12.Add(typeof(IXmlLineInfoProvider), new XmlLineInfoProvider(new XmlLineInfo(185, 53)));
				object target8 = setter4.Value = ((IMarkupExtension)staticResourceExtension8).ProvideValue((IServiceProvider)xamlServiceProvider12);
				VisualDiagnostics.RegisterSourceInfo(target8, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 185, 53);
				dataTrigger4.Setters.Add(setter4);
				VisualDiagnostics.RegisterSourceInfo(setter4, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 184, 46);
				((ICollection<TriggerBase>)label3.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger4);
				VisualDiagnostics.RegisterSourceInfo(dataTrigger4, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 181, 42);
				flexLayout2.Children.Add(label3);
				VisualDiagnostics.RegisterSourceInfo(label3, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 173, 34);
				image4.SetValue(VisualElement.HeightRequestProperty, 25.0);
				image4.SetValue(Image.AspectProperty, Aspect.AspectFit);
				image4.SetValue(View.MarginProperty, new Thickness(0.0, 0.0, 12.0, 0.0));
				bindingExtension14.Path = "TempsReel";
				BindingBase target9 = bindingCondition.Binding = ((IMarkupExtension<BindingBase>)bindingExtension14).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target9, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 195, 67);
				bindingCondition.Value = "True";
				multiTrigger.Conditions.Add(bindingCondition);
				bindingExtension15.Path = "Selected";
				BindingBase target10 = bindingCondition2.Binding = ((IMarkupExtension<BindingBase>)bindingExtension15).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target10, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 197, 67);
				bindingCondition2.Value = "True";
				multiTrigger.Conditions.Add(bindingCondition2);
				setter5.Property = Image.SourceProperty;
				setter5.Value = "checkboxchecked_red.png";
				setter5.Value = new ImageSourceConverter().ConvertFromInvariantString("checkboxchecked_red.png");
				multiTrigger.Setters.Add(setter5);
				VisualDiagnostics.RegisterSourceInfo(setter5, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 200, 46);
				((ICollection<TriggerBase>)image4.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)multiTrigger);
				bindingExtension16.Path = "TempsReel";
				BindingBase target11 = bindingCondition3.Binding = ((IMarkupExtension<BindingBase>)bindingExtension16).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target11, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 205, 67);
				bindingCondition3.Value = "True";
				multiTrigger2.Conditions.Add(bindingCondition3);
				bindingExtension17.Path = "Selected";
				BindingBase target12 = bindingCondition4.Binding = ((IMarkupExtension<BindingBase>)bindingExtension17).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target12, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 207, 67);
				bindingCondition4.Value = "False";
				multiTrigger2.Conditions.Add(bindingCondition4);
				setter6.Property = Image.SourceProperty;
				setter6.Value = "checkbox.png";
				setter6.Value = new ImageSourceConverter().ConvertFromInvariantString("checkbox.png");
				multiTrigger2.Setters.Add(setter6);
				VisualDiagnostics.RegisterSourceInfo(setter6, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 210, 46);
				((ICollection<TriggerBase>)image4.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)multiTrigger2);
				bindingExtension18.Path = "TempsReel";
				BindingBase target13 = dataTrigger5.Binding = ((IMarkupExtension<BindingBase>)bindingExtension18).ProvideValue((IServiceProvider)null);
				VisualDiagnostics.RegisterSourceInfo(target13, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 214, 54);
				dataTrigger5.Value = "False";
				setter7.Property = Image.SourceProperty;
				setter7.Value = "nontempsreel.png";
				setter7.Value = new ImageSourceConverter().ConvertFromInvariantString("nontempsreel.png");
				dataTrigger5.Setters.Add(setter7);
				VisualDiagnostics.RegisterSourceInfo(setter7, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 216, 46);
				((ICollection<TriggerBase>)image4.GetValue(VisualElement.TriggersProperty)).Add((TriggerBase)dataTrigger5);
				flexLayout2.Children.Add(image4);
				VisualDiagnostics.RegisterSourceInfo(image4, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 189, 34);
				listViewTemplateCell.View = flexLayout2;
				VisualDiagnostics.RegisterSourceInfo(flexLayout2, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 143, 30);
				return listViewTemplateCell;
			};
			radListView.SetValue(RadListView.ItemTemplateProperty, dataTemplate2);
			VisualDiagnostics.RegisterSourceInfo(dataTemplate2, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 140, 18);
			listViewItemStyle.SetValue(ItemStyle.BorderLocationProperty, Location.None);
			listViewItemStyle.SetValue(ItemStyle.BackgroundColorProperty, Color.Transparent);
			radListView.SetValue(RadListView.ItemStyleProperty, listViewItemStyle);
			VisualDiagnostics.RegisterSourceInfo(listViewItemStyle, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 227, 18);
			listViewUserCommand.Id = CommandId.ItemTap;
			bindingExtension6.Path = "ItemTapCommand";
			BindingBase binding5 = ((IMarkupExtension<BindingBase>)bindingExtension6).ProvideValue((IServiceProvider)null);
			listViewUserCommand.SetBinding(ListViewUserCommand.CommandProperty, binding5);
			radListView.Commands.Add(listViewUserCommand);
			VisualDiagnostics.RegisterSourceInfo(listViewUserCommand, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 231, 18);
			flexLayout.Children.Add(radListView);
			VisualDiagnostics.RegisterSourceInfo(radListView, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 90, 10);
			filtreLignesPage.SetValue(ContentPage.ContentProperty, flexLayout);
			VisualDiagnostics.RegisterSourceInfo(flexLayout, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 19, 6);
			VisualDiagnostics.RegisterSourceInfo(filtreLignesPage, new Uri("Views\\FiltreLignesPage.xaml", UriKind.RelativeOrAbsolute), 2, 2);
		}

		private void __InitComponentRuntime()
		{
			this.LoadFromXaml(typeof(FiltreLignesPage));
		}
	}
}
